# Generated by ShopOnline 4.2.5 on 2023-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Добавления продукта', 'verbose_name_plural': 'Добавлаения продуктов'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
