# Generated by ShopOnline 4.2.5 on 2023-10-03 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_remove_productmodel_category_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
